name: init
description: A sample command-line application.
version: 1.0.0
environment:
  sdk: '>=2.19.6'
dev_dependencies:
  build_runner: null
  source_gen: null
  yandex_maps_mapkit_lite:
    path: ../..
